### ISSUE TITLE
Produced food suddenly switched to consumed food

### ISSUE THREAD

**Issue by Carb0nNova** [deathraygames/civ-clicker#19]
I was producing about 10,000 food per second when suddenly I was consuming over 100,000 food.

Every time I add a farmer, the food consumption goes up instead of going down. Seems a variable may not be converted from positive to negative or vice-versa somewhere.

![Screen 1, no farmers](https://cloud.githubusercontent.com/assets/8889069/23752424/dc86d454-049a-11e7-93c6-9985cc60a816.PNG)
![Screen 2, after adding farmers](https://cloud.githubusercontent.com/assets/8889069/23752427/de3fb70c-049a-11e7-97ba-7beac4f31257.PNG)

**Comment by Carb0nNova** [comment]
After resetting and starting a new civilization, it seems to have gone back to normal.

**Comment by Lukenickerson** [comment]
@Carb0nNova -- Do you think you would be able to reproduce this?

**Comment by Carb0nNova** [comment]
Unfortunately not. I'm not entirely sure what I did to produce it in the first place. I believe I was building temples or raising zombies. I only noticed once I noticed my workers dying.

I'll keep an eye out for it as I play more.

**Comment by Lukenickerson** [comment]
@Carb0nNova -- Do you think this might have to do with losing your mills? I ran into the same issue, and I think it was due to some raiders destroying my mills, which killed my food production.

**Comment by Lukenickerson** [comment]
I think I found the bug and fixed it: https://github.com/deathraygames/civ-clicker/releases/tag/v1.3.3 ... The population counts were going negative which caused farmers to start destroying their crops.
Let me know if it happens again!
