### ISSUE TITLE
Can't select a deity, have enough piety.

### ISSUE THREAD

**Issue by ajman444** [deathraygames/civ-clicker#20]
The text implies that it requires 500 piety to select a deity, I've got more piety than that, but still am unable to make a selection.

Save file:

NobwRAbgpgTgzgSwPYDsAiBDALhsAucAWwwCskZ8BGAGjEIRXKtrgFcAjfAVgE5bCkAE3xgMAGwAOAC1wBfWgGNWMAMIII+cAvUA5DISgiA6kiFwsSBQGswtGKzGw9BkQHkYWKAjG2wALyRCdgRDAjAkAHcUKGE8AAZ5MABzGAxoTXComPwAJi4cxKhowgBPAGUxDAYMyOjYgBYAZkpEgVTHDIFYmjAoADM+hG0ihRKqADp6gDY8gHZG+vrKRq4pqbjZgrsoOCRlBSgVMSGrOHwpyi5G2mwcaxU9lE8KPEa4rlosVMFYTuxYBDiACSsTAEVMwm2AEdWDtPLEuHEkXFPggDC8UWAFI9nlQ1olUghYuBCYIGEl8H1xHAoLQIEMLDAxngqWIabQoBIkBJ8JiJGJWCgfjAADKmLCaRKVcwiXw4GBJKBYACyGAAHiI4MQxGIACq1MCJJQwExC35hFD6UJgXzmDCK3m0CQwJApHZneJ2VhwKTZFnUqCJcFm+D4YAAXVoPwQWBCHtAYEtLjwYHcnm8vkEgSqKFl/HVaCgGniskjYBkhEcWAAggopDUsrEvrDEvSdfaoLX62Fan7m4GWNq9bUuw26vh+1KMAqoPqoqOe42J/YB2AteIxGosCUF+Be7FWTSpzOtzu62O/YfVwYvtykMc4LvMuP/WzV+udXpY6gn/vKQHEktb8UF/JdXyPWhKhnL9kBA89FxfK9CkICQEBgTt4L3MCkNoPoIQvWIch4AAOJFaGiCVXkWepxh4KZZhmShZjiHgkWmIN8IQv1KEoZFyKVKgmPGJEuGI2YrjiYj8ik2ZEnMVBQiwl8eL4xMBLwHjZmE94xIkqSchkuSrAYD0lL9ZpGlmWZiMmSgmkYmYeGuNTKKacYpjE5YclmJyckoKY6MSX0YHYUznz9JYRP41zEnIRTwtiDziJsng7MaRjRJWepovwHh3M8xpvN8/y6PqKUoGwYKCKoOJ1jecZRNWSziKWVYcrwLTmgM+iclq6y3nS1olXEaqNP8gyuGEqSpma1qpnazrKG6zY+uIgapkSVClWZMzYnS+o8vE9Z5hWKTeHayapLiIjLKmLh6hyKYHp4RIknvYkEt5I1yAkGkwr/EsoyLJBgNGhJcPQqARQwIVRrspFEk8J44YR2gpFYSjdpq8GsRBnAHS4vbUfLPYaVG3qceIFBEFQMHEnYadc0J/BZjK2hwTMCxrFG+65IsaJ5O55m8F5z4YeiJkUbk+gsCkHbPo0nGMC5WWoAUad5YB3jEagFCOmF+ocYZmBUmsf6wO1lgcHYfWscV17UmgEppw+rXKe8HxhctsA8I8BBBnV0HheI+nbkcasxHlOncJCMRBEfSPp2jsBBWFcEYDjiOo+FnHA6zpOc6MhgUHJUbJzR6doHMUvhfLsBnSQOAJDV2MUApWuV0SLMDGrwPYLLzunTEPYkikH1px2AeW1oNCYAQJJsH7jvp7AdgMbrAE26n1cF5gH4S635fVygNUvgwBQg7tuu+kcama6vwe6HP2BF8Ph+V4UF0G5wS+FbrmlHAX3UFAdgkMyRvz/o/PosBYwPlgObRCAF8y7BQJLI+31qbNiAbTdBNwYB1hjC3ZQ8UAZ1yRrrIoWAEF9kfnAAUhBqFNkfikGG044zb02uIBAcAMA/A4ezCqXJUGazAv/KQsd478JJvAEB58bC4LBL6KAnt36rgiHPVu7dVGJF4fQEu5hUi/1IY/bEPwkA3wwBERhy4V7EFVnYoY1i8B1wwHCX0sYFBOLrtoNsNIYD0gOFI6BrBBBcK1FIpIrBvCSOFjhNcsA+hOLiUBWCYTCCjTienH0CAeQKIFOhDJSDcYoRhkvO2cTsSEF9pjBWcSbbunvrUopEQMDmBIdhIpdoRGILfASIkghbZNN6Z8KQLpoiFLfIoHEX1IJWmRrEop7BTDyPKUU6BrSakAziTST+SokmdJwEKF2Uiz58IWcMrEyh0IoFGBMiCxT0SBPOfcrUhDJS0CSMPNB4BYzohmWCE4sAqbvLBOIFZYBDGhBxoSGkhZeEgrYIQAQKAygyDOSATacIHhPBdCosAvzzQ4xYU8rQjdKK8WJoKXW/IkAlD9HbHGVK9a0piECHUycqQwD+cLRopEcacvRGyvFAMcYc0EEoLAuIvbrA4kICVzwhXJz0eaO2ht3YS0VYXMWKAJZS21Rq9lWrV6VDNjLbsdtvY2zka82WmqGVBQqo4F4FrMTGkONMwG5ZHWwDtQrXOTqhijUNkaANChfUiqnEs4hzq/WRr2OhGA4awI412HHEIMa3YpveumpNL5c5pHEN8hWFKjQFrEEyXNfp82bLAlsNcaL2l5o4mIPoycGZChjG26cxtARM3tRyRAUACb9rXNm2AAAFac25k7qwgIWkok6PDdKrXJEIw7Y0DrHRm5NhRqnJ1JLAUCL465FCSAwKAh7MJDPud3Bgi8fxXq2UUmQ8Ij2XiKcPaAgg30HiKXnR9ojmFQXJD+/8FyFDDwiMKUD4FVz8ntLCb9AGen3NHmSuccFzXXtXAzSV4dkPvouYMZR8cYNxNTrAdOmcCO/vA9gR8NGwP3L6A4MQAAJUmGEsNPoucGaDjHYNySLEUMjRTHkyCeKJi59gfQxCk/c6I0B8HHGsPJwMshSxAA=

**Comment by Lukenickerson** [comment]
Also from https://www.reddit.com/r/incremental_games/comments/5y1pfy/continuation_of_civclicker_with_updated_interface/

> I earn 430 piety per second and haven't chosen my first deity. But the selection buttons are all greyed out. I tried refreshing the page, resetting and re-importing the save, but nothing did it.

**Comment by Lukenickerson** [comment]
Fixed. New version will be released momentarily.
