### ISSUE TITLE
Add progress bars

### ISSUE THREAD

**Issue by olleharstedt** [deathraygames/civ-clicker#38]
Things happen too fast. Progress bars for research and buildings and the like could help. Compare with Diablo 3 and the time it takes to construct weapons (approx 2 sec).

**Comment by Lukenickerson** [comment]
Do you mean to add a time element to constructing buildings? I thought about that but struggled with both where to put it on the UI, and how to scale it so you're not waiting forever once you're building hundreds of buildings ar a time. It is something worth considering and designing though.

**Comment by olleharstedt** [comment]
I'm testing out progress bars on my branch, too. I thought the time could simply be calculated from the price, i.e. the amount of wood, stone, etc, where each wood adds 1 millisecond, each stone 2 milliseconds, or something like that.

**Comment by olleharstedt** [comment]
What do you think about this?

![Example of progress bar](http://pasteboard.co/Lq0F8AcT8.gif)

**Comment by Lukenickerson** [comment]
@olleharstedt -- Yeah, that's a good placement for the progress bar.

**Comment by olleharstedt** [comment]
Done in my fork, but needs to be configurable probably (because it was not a popular change).
