### ISSUE TITLE
Add paleolithic phase

### ISSUE THREAD

**Issue by olleharstedt** [deathraygames/civ-clicker#39]
This is a bigger concept. It would be nice to start earlier than Neolithics (which is when agriculture were developed). You can make hunter-gatherer groups, research bows, fire, stone tools, and ceramics. All this as a pre-phase to civilization. The ice-age could be part of it, too.

**Comment by Lukenickerson** [comment]
I love this idea. I actually recently sketched up ideas for a game based entirely in this period (for a caveman themed game jam).  

It would be cool to add this to CivClicker, but it would definitely a big lift. After considering the massive amount of refactoring needed, I've been hesitant to consider big new features. But if we could get there, it would be nice.

**Comment by olleharstedt** [comment]
I hear you. :)

Maybe we should extend the event system? The goal of refactoring should be to make it possible to add new functionality _without_ touching old code. See the function `doFarmer`, for example. To add a new farming boost, this function would need to be edited. If it instead fires an event that objects can subscribe to, it would be possible to add farming boost without touching it. The whole system can be built up like this.

**Comment by Lukenickerson** [comment]
Making things extensible would be great, but probably worth a separate ticket for each part of the game.

**Comment by olleharstedt** [comment]
Working on this in my own fork, so closing it here.
