### ISSUE TITLE
Getters and setters in civclicker-classes.js

### ISSUE THREAD

**Issue by olleharstedt** [deathraygames/civ-clicker#44]
AFAIK, getters and setters are not standard in Javascript, yet. Are you using a tool to transpile the code to ES5? Maybe this should be noted in the README.

**Comment by olleharstedt** [comment]
Maybe I was wrong about this. Mozilla lists "Basic support" for all major browsers: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

**Comment by Lukenickerson** [comment]
Yeah, i think support goes back a ways, to IE9. I'll close this, but reopen if you think it'll be an issue.
