### ISSUE TITLE
Use a CSS framework

### ISSUE THREAD

**Issue by olleharstedt** [deathraygames/civ-clicker#45]
We should probably use Bootstrap, Foundation or something like it. E.g., why use pure Javascript modals instead of a nice framework modal?

**Comment by olleharstedt** [comment]
I'm working on this on my branch now. Will post picture later.

**Comment by olleharstedt** [comment]
![Preview](https://snag.gy/3BFHvA.jpg)

**Comment by Anahkiasen** [comment]
Nice, that would allow a theme switcher such as what Swarmsim has.

**Comment by olleharstedt** [comment]
Cool, that's more than I knew. BS4 is still in alpha, AFAIK.

**Comment by olleharstedt** [comment]
I actually implemented this. Or rather, added the few dependencies needed to do it automatically. See "Theme selector" in settings: http://31.24.227.106/

**Comment by olleharstedt** [comment]
Fixed in my fork.
