### ISSUE TITLE
Choose a framework for unit-tests

### ISSUE THREAD

**Issue by olleharstedt** [deathraygames/civ-clicker#48]
I've used QUnit before and was pretty happy with that, will try it in my fork.

https://qunitjs.com/

**Comment by Anahkiasen** [comment]
If you haven't taken a look at it I highly recommend [Jest](https://facebook.github.io/jest/), in particular the snapshot feature is very useful.

**Comment by olleharstedt** [comment]
OK, will have a look.

**Comment by olleharstedt** [comment]
Here's a comparison page: https://stackshare.io/stackups/jest-vs-mocha-vs-qunit

**Comment by olleharstedt** [comment]
But if you use Jest at work, let's pick that one.

**Comment by Lukenickerson** [comment]
I added jest as a dev dependency. We'll need some tests, but I think those can wait until there's been more refactoring.

**Comment by olleharstedt** [comment]
Cool. So you accept pull requests? I did some work on a fork some years ago[1]. Maybe some of those changes can be moved over to the main repo, piece by piece? With some discussion.

[1] http://olleharstedt.github.io/civclicker/2017/10/28/civclicker2-progress-report.html
