### ISSUE TITLE
Put functions into modules and namespaces

### ISSUE THREAD

**Issue by olleharstedt** [deathraygames/civ-clicker#49]
There's a lot of polluting of the global namespace. I suggest we use modules and namespaces in the following fashion:

```javascript
/**
 * @namespace
 */
var CivClicker = CivClicker || {};

CivClicker.utils = (function() {
  
  // Private function encapsulated by the closure
  var privateFunction = function() {};

  // Public functions go into the returning object.
  return {
    someFunction: function() {}
  };
})();

**Comment by Anahkiasen** [comment]
For the note if you're willing to go there you can always use a transpiler [such as Babel](https://babeljs.io/) which would allow you to leverage ES6+ syntax such as classes and imports/exports while still compiling to normal code.

**Comment by olleharstedt** [comment]
I know. I've tried it and was not impressed, so I think I'll try to keep it pure Javascript.
