### ISSUE TITLE
Add a "Add all unemployed workers" button

### ISSUE THREAD

**Issue by gabahulk** [deathraygames/civ-clicker#62]
Hello!
I've often in the beginning of the game, have trouble with assigning workers. I think it would be a nice Ux change to add a button that assigns all unemployed workers to a work

**Comment by Lukenickerson** [comment]
Later on there is a `+∞` button that allows you to do this, but you have to "unlock" it by playing the game a little more. The beginning can be a little tedious, but for an incremental that's honestly part of the appeal.
